app/urls.py
from django.urls import path
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView
from . import views

# app_name = 'app'

urlpatterns = [
    path('',  ItemFilterView.as_view(), name='index'),
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    # path('detail/', ItemDetailView.as_view(), name='detail'),
    path('create/', ItemCreateView.as_view(), name='create'),
    # path('create/', views.create, name='create'),
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
    path('invitation/', views.invitation, name='invitation'),
    path('thanks/', views.thanks, name='thanks'),
    path('access/', views.access, name='access'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

]

app/models.py
from django.db import models
from django.core import validators


class Item(models.Model):

    SEX_CHOICES = (
        (1, 'ご出席'),
        (2, 'ご欠席'),
    )

    name = models.CharField(
        verbose_name='ご芳名',
        max_length=200,
    )
    tel = models.CharField(
        verbose_name='お電話',
        max_length=200,
        null=True,
    )
    # addres = models.CharField(
    #     verbose_name='住所',
    #     max_length=200,
    # )
    # age = models.IntegerField(
    #     verbose_name='年齢',
    #     validators=[validators.MinValueValidator(1)],
    #     blank=True,
    #     null=True,
    # )

    yubin = models.CharField(
        verbose_name='ご住所',
        max_length=200,
        null=True,
    )
    address = models.CharField(
        verbose_name='',
        max_length=200,
        null=True,
    )

    sex = models.IntegerField(
        verbose_name='どちらかをお選びください',
        choices=SEX_CHOICES,
        default=1
    )
    memo = models.TextField(
        verbose_name='メッセージ',
        max_length=300,
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(
        verbose_name='登録日',
        auto_now_add=True
    )

    # 管理サイト上の表示設定
    def __str__(self):
        return self.name
        
    class Meta:
        verbose_name = 'name'
        verbose_name_plural = 'name'

app/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ('sex','name','yubin','address','tel','memo')
        # fields = ('tel')
            # ('addres')
        widgets = {
                    'name': forms.TextInput(attrs={'placeholder':'わだ　にゃん太郎'}),
                    'tel': forms.TextInput(attrs={'placeholder':'1234567890'}),
                    # 'addres': forms.TextInput(attrs={'placeholder': '記入例：大阪府豊中市蛍池〇〇番地'}),
                    'yubin': forms.TextInput(attrs={'placeholder': '郵便番号'}),
                    # 'age': forms.NumberInput(attrs={'min':1}),
                    'sex': forms.RadioSelect(),
                    'address': forms.Textarea(attrs={'rows': 2, 'placeholder': '大阪府門真市門真1006番地'}),
                    'memo': forms.Textarea(attrs={'rows':4, 'placeholder':'記入例：乾杯はみかんジュースで'}),
                  }

app/views.py
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from .filters import ItemFilter
from .forms import ItemForm
from .models import Item

from django.shortcuts import render

# # Create your views here.
# # 検索一覧画面
class ItemFilterView(FilterView):
    model = Item
#
#     # デフォルトの並び順を新しい順とする
#     queryset = Item.objects.all().order_by('-created_at')
#
#     # django-filter用設定
#     filterset_class = ItemFilter
#     strict = False
#
#     # 1ページあたりの表示件数
#     paginate_by = 10
#
#     # 検索条件をセッションに保存する
#     def get(self, request, **kwargs):
#         if request.GET:
#             request.session['query'] = request.GET
#         else:
#             request.GET = request.GET.copy()
#             if 'query' in request.session.keys():
#                 for key in request.session['query'].keys():
#                     request.GET[key] = request.session['query'][key]
#
#         return super().get(request, **kwargs)

# # 検索一覧画面
# class ItemFilterView(LoginRequiredMixin, FilterView):
#     model = Item
#
#     # デフォルトの並び順を新しい順とする
#     queryset = Item.objects.all().order_by('-created_at')
#
#     # django-filter用設定
#     filterset_class = ItemFilter
#     strict = False
#
#     # 1ページあたりの表示件数
#     paginate_by = 10
#
#     # 検索条件をセッションに保存する
#     def get(self, request, **kwargs):
#         if request.GET:
#             request.session['query'] = request.GET
#         else:
#             request.GET = request.GET.copy()
#             if 'query' in request.session.keys():
#                 for key in request.session['query'].keys():
#                     request.GET[key] = request.session['query'][key]
#
#         return super().get(request, **kwargs)


#
# 詳細画面
class ItemDetailView( DetailView):
    model = Item

# # 詳細画面
# class ItemDetailView(LoginRequiredMixin, DetailView):
#     model = Item


# 登録画面
class ItemCreateView(CreateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('thanks')

# 更新画面
class ItemUpdateView(UpdateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')


# 削除画面
class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('index')



def invitation(request):
    # post = get_object_or_404(Post, pk=pk )
    return render(request, 'app/invitation.html', {})

def thanks(request):
    return render(request, 'app/thanks.html', {})

def access(request):
    return render(request, 'app/access.html', {})

# def create(request):
#     if request.method == 'POST':
#         form_class = ItemForm(request.POST)
#         if form_class.is_valid():
#             model = form_class.save(commit=False)
#             model.save()
#             return redirect('index', pk=form_class.pk)
#     else:
#         form_class = ItemForm
#     return render(request, 'app/thanks.html', {'form': form_class})

app/templates/app/_base.html
{% load static %}
<html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>WebInv1019</title>
    <!-- Bootstrap CSS -->
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "app/css/app.css" %}" rel="stylesheet">
</head>

<body>
<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--        <a class="navbar-brand" href="#">アプリケーション名</a>-->
<!--        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"-->
<!--            aria-label="ナビゲーションの切替">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->

<!--        <div class="collapse navbar-collapse" id="Navber">-->
<!--            <ul class="navbar-nav mr-auto">-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'admin:index'%}">管理サイト</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'admin:logout'%}">ログアウト</a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--        &lt;!&ndash; /.navbar-collapse &ndash;&gt;-->
<!--    </nav>-->
    {% block content %} 
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static "app/js/plugins/responsive-paginate.js" %}"></script>
    <script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

app/templates/app/access.html
{% extends "./_base.html" %}
{% block content %}
{% load static %}

<div class="jumbotron-Access">
        <center>
            <h1>　</h1>
            <h1>　</h1>
            <h3><img src="{% static "app/img/アクセスページ/アクセスページ@3x.png"%}" width="300px"/></h3>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3280.4610716451525!2d135.5017901155539!3d34.693548880436346!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6000e6e7cca81681%3A0x35904a0741816399!2z5aSn6Ziq5biC5Lit5aSu5YWs5Lya5aCC!5e0!3m2!1sja!2sjp!4v1566171066469!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
<!--            <h3><img src="{% static "app/img/入力完了ページ/P1001183.JPG"%}" width="700px"/></h3>-->
             <h1>　</h1>
            <h2>大阪市中央公会堂</h2>
            <h2>大阪市北区中之島１−１−２７</h2>
            <h2>TEL 06-6208-2002</h2>
<!--            <h1>MAP</h1>-->
            <h1>　</h1>
            <h3><img src="{% static "app/img/アクセスページ/最寄り駅表@3x.png"%}" class="img-fluid"/></h3>
            <h1>　</h1>
            <h3><img src="{% static "app/img/アクセスページ/会場入口図@3x.png"%}" class="img-fluid"/></h3>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>ここは画像</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h2>国の重要文化財である公会堂の</h2>
            <h2>1階部分は見学自由となっております。</h2>
            <h2>お時間ございましたら是非ご見学されて下さい！</h2>
            <h1>　</h1>
                        <div class="float-right">
            <h3><a class="btn btn-circle-3d" href="{% url 'index' %}"><img src="{% static "app/img/入力完了ページ/ホームアイコン@3x.png"%}" width="150px"/></a>　</h3>
            <!--            <h1><a href="{% url 'index' %}"><img src="{% static "app/img/入力アイコン.png"%}" width="250px"/></a></h1>-->
        </div>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>

        </center>


</div>
{% endblock %}

app/templates/app/invitation.html
{% extends "./_base.html" %}
{% block content %}
{% load static %}
<div class="jumbotron-inv">
        <center>
            <h2>　</h2>
            <h3><img src="{% static "app/img/インフォメーションページ/インフォメーションアイコン@3x.png"%}" width="300px"/></h3>
            <h2>　</h2>
            <h3><img src="{% static "app/img/インフォメーションページ/P1001464.JPG"%}" class="img-fluid"/></h3>
            <h2>　</h2>
            <h2>　</h2>
            <h3><img src="{% static "app/img/インフォメーションページ/日時詳細文@3x.png"%}" class="img-fluid"/></h3>
<!--        <div>-->
<!--            <h2>　　　日時　　　　２０１９年１０月１９日（土曜日）　　　　</h2>-->
<!--            <h2>　　　受付　　　　正午　　　　　　　　</h2>-->
<!--            <h2>　　　挙式　　　　午後１２時３０分　　</h2>-->
<!--            <h2>　　　披露宴　　　午後１時３０分　　　</h2>-->
<!--        </div>-->
<!--        <div>-->
<!--            <h2>　</h2>-->
<!--            <h2>　　　場所　　　　大阪中央公会堂　　　　　　　　　　　　　</h2>-->
<!--            <h2>　　　挙式　　　　３階特別室　　　　　</h2>-->
<!--            <h2>　　　披露宴　　　３階中集会室　　　　</h2>-->
<!--        </div>-->
        <div>
            <h2>　</h2>
            <h2>　</h2>
            <h2>　</h2>
            <h2>誠に勝手ながら9月15日迄にご返信</h2>
            <h2>いただければ幸いに存じます</h2>
        </div>
        <div>
            <h2>　</h2>
            <h1><a href="{% url 'create'  %}"><img src="{% static "app/img/インフォメーションページ/RSVPアイコン@3x.png"%}" width="500px"/></a></h1>
            <h2>　</h2>
        </div>
        </center>
</div>
{% endblock %}

app/templates/app/item_card.html
<div class="row">
    <div class="col-3">
        <p>名前</p>
    </div>
    <div class="col-9">
        <p>{{ item.name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>年齢</p>
    </div>
    <div class="col-9">
        <p>{{ item.age }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>性別</p>
    </div>
    <div class="col-9">
        <p>{{ item.get_sex_display }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>備考</p>
    </div>
    <div class="col-9">
        <p>{{ item.memo|linebreaksbr }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>登録日</p>
    </div>
    <div class="col-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>

app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
<div class="container">
    <h2 class="text-center">データ削除</h2>
    <p>このデータを削除します。よろしいですか？</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
        {% include "./item_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
	<h2 class="text-center">詳細表示</h2>
	<div class="row">
		<div class="col-12">
			<a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
		</div>
	</div>
	<!--  -->
	{% include "./item_card.html" %}
	<div class="row">
		<div class="col-12">
			<a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
		</div>
	</div>
</div>


        <center>
        <img src="{% static "app/img/インフォメーションピクト.png"%}" width="250px"/>
        <div>
            <h2>2019年10月19日（土曜日）</h2>
            <h2>受付　11時xx分</h2>
            <h2>受付　12時xx分</h2>
            <h2>披露宴　13時xx分</h2>
        </div>
        <div>
            <h2>大阪中央公会堂</h2>
            <h2>にゃんご</h2>
            <h2>にゃんご</h2>
        </div>
        <div>
            <h2>返信をお願い致します</h2>
        </div>
        <div>

            <h1><a href="{% url 'create'  %}"><img src="{% static "app/img/入力アイコン.png"%}" width="250px"/></a></h1>

        </div>
        </center>

{% endblock %}

app/templates/app/item_filter.html
{% extends "./_base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<!--<div class="container">-->
<!--	<div id="myModal" class="modal fade" tabindex="-1" role="dialog">-->
<!--		<div class="modal-dialog" role="document">-->
<!--			<div class="modal-content">-->
<!--				<div class="modal-header">-->
<!--					<h5 class="modal-title">検索条件</h5>-->
<!--					<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">-->
<!--						<span aria-hidden="true">&times;</span>-->
<!--					</button>-->
<!--				</div>-->
<!--				<form id="filter" method="get">-->
<!--					<div class="modal-body">-->
<!--						{{filter.form|crispy}}-->
<!--					</div>-->
<!--				</form>-->
<!--				<div class="modal-footer">-->
<!--					<a class="btn btn-outline-secondary" data-dismiss="modal">戻る</a>-->
<!--					<button type="submit" class="btn btn-outline-secondary" form="filter">検索</button>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--	<div class="row">-->
<!--		<div class="col-12">-->
<!--			<a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>-->
<!--			<div class="float-right">-->
<!--				<a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>-->
<!--				<a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

<!--	<div class="row" >-->
<!--		<div class="col-12">-->
<!--			{% include "./_pagination.html" %}-->
<!--		</div>-->
<!--	</div>-->

<!--	<div class="row">-->
<!--		<div class="col-12">-->
<!--			<ul class="list-group">-->
<!--				{% for item in item_list %}-->
<!--				<li class="list-group-item">-->
<!--					<div class="row">-->
<!--						<div class="col-3">-->
<!--							<p>名前</p>-->
<!--						</div>-->
<!--						<div class="col-9">-->
<!--							<p>{{ item.name }}</p>-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="row">-->
<!--						<div class="col-3">-->
<!--							<p>登録日</p>-->
<!--						</div>-->
<!--						<div class="col-9">-->
<!--							<p>{{item.created_at|date:"Y/m/d G:i:s"}}</p>-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="row">-->
<!--						<div class="col-12">-->
<!--							<div class="float-right">-->
<!--								<a class="btn btn-outline-secondary " href="{% url 'detail' item.pk %}">詳細</a>-->
<!--								<a class="btn btn-outline-secondary " href="{% url 'update' item.pk %}">編集</a>-->
<!--								<a class="btn btn-outline-secondary " href="{% url 'delete' item.pk %}">削除</a>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--				</li>-->
<!--				{% empty %}-->
<!--				<li class="list-group-item">-->
<!--					対象のデータがありません-->
<!--				</li>-->
<!--				{% endfor %}-->
<!--			</ul>-->
<!--		</div>-->
<!--	</div>-->
<!--	<div class="row" >-->
<!--		<div class="col-12">-->
<!--			<div class="float-right">-->
<!--				<a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>-->
<!--				<a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->
<div class="jumbotron-TOP">
    <div class="container">
    <center>
        <h2>　</h2>
        <h2><img src="{% static "app/img/TOPページ/TOP_大阪中央公会堂@3x.png" %}" class="img-fluid"/></h2>
        <h2><img src="{% static "app/img/TOPページ/TOP_Wedding Invitation@3x.png" %}" class="img-fluid"/></h2>
        <h2><img src="{% static "app/img/TOPページ/P1001910.png" %}" class="img-fluid"/></h2>
        <h3><img src="{% static "app/img/TOPページ/TOP_2019.10.19  Sat@3x.png" %}" class="img-fluid"/></h3>
        <h2>　</h2>
        <h3><img src="{% static "app/img/TOPページ/TOP_挨拶文@3x.png" %}" class="img-fluid"/></h3>


<!--                     <div>-->
<!--                         <h2>謹啓  季夏の候　皆様にはますますご清祥のことと<h2>-->
<!--                         <h2>お慶び申し上げます</h2>-->
<!--                     </div>-->
<!--                     <div>-->
<!--                         <h2>このたび　私たちは結婚式を挙げることとなりました</h2>-->
<!--                         <h2>つきましては　日頃お世話になっております皆様に</h2>-->
<!--                         <h2>感謝の気持ちを込めて　ささやかな小宴を催したく存じます</h2>-->
<!--                     </div>-->
<!--                     <div>-->
<!--                         <h2>ご多用中　誠に恐縮ではございますが</h2>-->
<!--                         <h2>ぜひご出席をいただきたく　ご案内申し上げます</h2>-->
<!--                     </div>-->
<!--                     <div>-->
<!--                         <h2>　　　　　　　　　　　　　　　　　　　　　　　　　謹白</h2>-->
<!--                         <h2>2019年8月吉日 </h2>-->
<!--                         <h2>鈴木　崇史 </h2>-->
<!--                         <h2>盛　惇子 </h2>-->
<!--                     </div>-->
<!--                     <div>-->
        <h2><a href="{% url 'invitation' %}"><img src="{% static "app/img/TOPページ/TOP_インフォメーション@3x.png"%}" width="500px"/></a></h2>
<!--        <a href="https://goo.gl/maps/pJLducd8Eb9YTRm19"><img src="{% static "app/img/TOPページ/TOP_アクセス@3x.png"%}" class="img-fluid"/></a>-->
        <a href="{% url 'access' %}"><img src="{% static "app/img/TOPページ/TOP_アクセス@3x.png"%}" width="500px"/></a>
        <h2><a href="{% url 'create' %}"><img src="{% static "app/img/TOPページ/TOP_RSVP@3x.png"%}" width="500px"/></a></h2>
        <h2>　</h2>
        <h2>　</h2>
    </center>
    </div>
</div>
{% endblock %}

app/templates/app/item_form.html
{% extends "./_base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
{{ form.certifications.errors }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <center>
                <h3><img src="{% static "app/img/入力ページ/RSVPページ@3x.png"%}" width="150px"/></h3>
            </center>
        </div>
    </div>
<!--    <div class="row">-->
<!--        <div class="col-12">-->
<!--            <div class="float-right">-->
<!--                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>-->
<!--&lt;!&ndash;                <a class="btn btn-outline-secondary save" href="#">保存</a>&ndash;&gt;-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {%crispy form%}
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div align="center">
<!--                <form action="" method="POST">-->
<!--                    {% csrf_token %}-->
<!--                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>-->
<!--                <h1><a href="#"><img src="{% static "app/img/送信アイコン.png"%}" width="250px"/></a></h1>-->
                    <a class="btn btn-circle-3d save" href="#"><img src="{% static "app/img/入力ページ/送信アイコン@3x.png"%}" width="100px"/></a>
                    <a class="btn btn-circle-3d save" href="{% url 'thanks' %}">aaa</a>
                    <button type="submit" class="save btn btn-default">Save</button>
<!---->
                    {% csrf_token %}
<!--                    <a class="save" type="save" href="#"><img src="{% static "app/img/送信アイコン.png"%}" width="100px"/></a>-->
<!---->
<!--                </form>-->

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/thanks.html
{% extends "./_base.html" %}
{% block content %}
{% load static %}

<div class="jumbotron-Thanks">
        <center>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h3><img src="{% static "app/img/入力完了ページ/P1001183.JPG"%}" class="img-fluid"/></h3>
            <h3><img src="{% static "app/img/入力完了ページ/thanksyouアイコン@3x.png"%}" class="img-fluid"/></h3>
            <h1>送信完了しました</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
        </center>
        <div class="float-right">
            <h3><a class="btn btn-circle-3d" href="{% url 'index' %}"><img src="{% static "app/img/入力完了ページ/ホームアイコン@3x.png"%}" width="150px"/></a>　　　</h3>
            <!--            <h1><a href="{% url 'index' %}"><img src="{% static "app/img/入力アイコン.png"%}" width="250px"/></a></h1>-->
            <h1>　</h1>
            <h1>　</h1>
            <h1>　</h1>
        </div>

</div>
{% endblock %}